### ISSUE TITLE
Rough cost estimate of 10 boards

### ISSUE THREAD

**Issue by happytm** [azmat-bilal/bldc_motor_controller_pcb#1]
can you please provide rough estimate of 10 boards including parts  & PCB's ?

Thanks.

**Comment by azmat-bilal** [comment]
i have added mouser BOM (with mouser part numbers). it can be used to estimate realtime cost for 10 units using https://eu.mouser.com/create-bom/

**Comment by azmat-bilal** [comment]
for PCBs, it depends on the manufacturer and leadtime. its a simple 4 layer pcb so shouldnt cost more than 200 euros.

**Comment by happytm** [comment]
@azmat-bilal  Thanks.
