### ISSUE TITLE
Corresponding to which version and voltage of ODrive?

### ISSUE THREAD

**Issue by TDA-2030** [azmat-bilal/bldc_motor_controller_pcb#3]
Recently, I plan to flash firmware to the board, but I can't find version info on silk screen, so I don't know which firmware to download [here](https://github.com/odriverobotics/ODrive/releases). Please point out the correct firmware.

**Comment by azmat-bilal** [comment]
i have tested it with v0.4.1. it should also work with v0.4.11. 

for versions v0.5+ it will not work out of the box as there is a firmware change were the controller waits for both drivers to get online at boot. there is a short fix mentioned in detail here https://discourse.odriverobotics.com/t/solved-new-firmware-odrive-tool-v5-1-for-3-4-24v-custom-board-one-axis/5805
